MINGW_DIR = C:/MinGW

all:
	@g++ -O0 -g3 -Wall src/cg1.cpp src/connection.cpp src/graphviewer.cpp src/main.cpp src/strings.cpp -o bin/CG2.exe $(MINGW_DIR)/lib/libwsock32.a 
clean:
	@del /Q /F /S CG2.exe